name = "Mistmint Haven"
free_feed_url = "https://www.mistminthaven.com/feed/"
novels_api_url = "https://api.mistminthaven.com/api/my-novels"
chapters_api_url = "https://api.mistminthaven.com/api/novels/slug/{slug}/chapters"
comments_api_url = "https://api.mistminthaven.com/api/comments/trans/all-comments"
translator = "CannibalTurtle"
translator_url = "https://www.mistminthaven.com/account/@CannibalTurtle-5082"
host_logo = "https://www.mistminthaven.com/images/mascot_mistmint.png"
host_emoji = "<:mascot_mistmint:1517514042930106559>"
coin_emoji = "<:mistmint_currency:1433046707121422487>"
ticket_emoji = "<:mistmint_ticket:1517453566632001597>"
token_secret = "MISTMINT_COOKIE"

