[row]
content = "{role_mention} ༺♡༻ {delta_text}\n> <:kawaiiaccents:1435916448890617948> ̟ !! ***{count} total readers***"

[message]
mode = "classic"
content = "{global_mention}\n"
allowed_mentions = { parse = ["roles"] }

[[message.embeds]]
author = { name = "Novel Updates", icon_url = "https://www.novelupdates.com/appicon.png" }
title = """
╔══.·:·.☽✧    ✦    ✧☾.·:·.══╗
          **weekly NU report**
╚══.·:·.☽✧    ✦    ✧☾.·:·.══╝"""
description = "{description}"
footer = { text = "Data retrieved" }
timestamp = "{timestamp}"
color = "{embed_color}"

[settings]
embed_color = "2D3F51"
allow_role_pings = true
global_mention_role = "admin"
hide_global_mention = true
no_data_text = "_No data this week (no NU counts retrieved)._"
