host = "Mistmint Haven"
title = "After Transmigrating into a Book, the Hot-Tempered Little Marquis Starts Training Dogs"
short_code = "ATBHTLM"

novelupdates_url = "https://www.novelupdates.com/series/after-transmigrating-into-a-book-the-hot-tempered-little-marquis-starts-training-dogs"
novel_url = "https://www.mistminthaven.com/novels/after-transmigrating-into-a-book-the-hot-tempered-little-marquis-starts-training-dogs"
featured_image = "https://web-novel-mistmint.s3.ap-southeast-1.amazonaws.com/novels/49ff5fa3-dc0a-4080-b2e3-9dcfbd4f8fa3.jpg"
novel_id = "baf022a2-a47a-4efe-9986-c0bf1e813379"

chapter_count = "120 Chapters"
last_chapter = "Chapter 120"
start_date = "21/7/2026"
has_free = true
has_paid = true
is_nsfw = false
is_membership = false

discord_color = "#14191c"

tags = ["chinese", "transmigration", "historical", "bl"]
site_genres = ["Romance", "Fantasy", "Aristocracy", "Transmigration", "Yandere", "Historical", "Yaoi"]

custom_description = """
【Soft and Adorable but Vicious Shou × Love-Brained, Unhinged Gong】

Su Chenchen transmigrated into a book.

He became a vicious cannon fodder character in the novel who relied on his looks and family background to stir up trouble and bully people wherever he went.

For example, the universally adored protagonist.

For example, his domineering fiancé.

And then there was the original host’s younger brother.

……

He had thought he could continue living such a carefree life.

But at some point, things gradually began slipping out of his control.

The universally adored protagonist was nothing like a pure and radiant white moonlight. Instead, he was more like a mad dog. On the surface, he was an aloof flower on a lofty peak, far beyond anyone’s reach, but in private, all he wanted was to…

His fiancé, who had always disliked him, began looking at him differently after realizing that he was the person he’d fallen for at first sight…

The original host’s younger brother had only coveted his title before, so why did he have his sights set on him now too???

Su Chenchen (horrified): Don’t come any closer!!!
"""
