host = "Mistmint Haven"
title = "Whose Simping Male Supporting Character Is Being Held and Kissed by the Male Lead?"
short_code = "WSMSC"

novelupdates_url = "https://www.novelupdates.com/series/whose-simping-male-supporting-character-is-being-held-and-kissed-by-the-male-lead"
novel_url = "https://www.mistminthaven.com/novels/whose-simping-male-supporting-character-is-being-held-and-kissed-by-the-male-lead"
featured_image = "https://i.imgur.com/zea8LXV.png"
novel_id = "4ee66cf7-3d4f-4cd1-b958-8a2dac6e167b"

chapter_count = "160 chapters + 3 extras"
last_chapter = "Afterword 2"
has_free = true
has_paid = true
is_nsfw = false
is_membership = false

discord_color = "#8a95a7"

tags = ["chinese", "reincarnation", "angst", "bl"]

custom_description = """
【Universal-darling shou, bittersweet tone, sour first then sweet, livestream variety show, shura-field free-for-all, double male leads, double purity, HE】
Wen Yanyu, a cannon-fodder supporting male universally hated online for obsessively clinging to the male lead and dragging himself into public controversy, suddenly awakens self-awareness and gets bound to a system, sent off to take missions.
After countless cycles that grind him down in both body and mind, Wen Yanyu returns in a body shattered by missions. He decides to give up trying, planning to muddle through the variety show the company lined up for him and earn a bit of retirement money.
Who would have thought that on what should have been a show meant to turn him into a laughingstock, the other guests’ gazes start getting stranger and stranger. Odd physical contact. Unexplained shura-fields.
Netizens who once angrily cursed him begin piecing things together from every tiny detail. His almost self-punishing behavior. His complete disregard for his own life. The doctor’s on-show medical pronouncement of impending death. And finally, the scar that nearly severed him at the waist. They all fell silent.
“Wuwu, how much has my wife suffered? I’ve caught a disease where I cry the moment I see my wife!”
“Wife, don’t like Fu Hanchuan anymore, okay? Be with us instead.”
——
The once ice-cold male lead who despised him to the extreme abandons his work, chases the variety show, follows him wherever he goes, blocks every rival, and because of one of his fevers, is so frightened that he breaks down crying in front of everyone.
Holding him in his arms, kissing him while coaxing him, his voice trembling with fear: “Good baby will live to a hundred years old, happy and safe.”
Netizens: redefining ‘hate to the extreme’. Fu Hanchuan! You brat, keep your hands off my bunny baby!
"""
