name: Check RSS and Send to Discord

on:
  schedule:
    - cron: "0 16 * * *"  # Runs daily at 16:00 UTC (backup schedule)
  workflow_dispatch:  # Allows manual trigger

jobs:
  rss_to_discord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install feedparser requests

    - name: Run RSS Checker
      run: python new_arc_rss_checker.py
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    - name: Commit updated arc_history.json if changed
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add arc_history.json || echo "arc_history.json not found"
        git diff --cached --quiet || (git commit -m "Update arc_history.json" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
