name: Send Token Alert to Discord

on:
  repository_dispatch:
    types: [token-expiring]

permissions:
  contents: read

jobs:
  send_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests

      - name: Send Discord alert
        env:
          DISCORD_BOT_TOKEN:      ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_MOD_CHANNEL_ID: ${{ secrets.DISCORD_MOD_CHANNEL_ID }}
          GITHUB_REPOSITORY:      ${{ github.repository }}
          GITHUB_EVENT_PATH:      ${{ github.event_path }}
        run: python scripts/send_token_alert.py
